networks:
  actor:
    state_dim: 11 # num_features
    action_dim: 1
    lr: 2e-4

  critic:
    global_state_dim: 275 # 12 * 8 = 96 (num_houses * num_features)
    lr: 8e-5

agent:
  k_epochs: 21
  gamma: 0.99
  eps_clip: 0.25
  entropy_coeff: 4e-4


data:
  path: "data\\IDEAL\\panel_env_ready_15m_50agents.csv.gz"


main:
  num_episodes: 500
  num_agents: 25
  update_interval: 17
  num_steps_per_day: 96

env: 
  ratio_clip_min_max: [0, 3.0]
  total_price_clip_min_max: [0.5, 2.0]
  scaling_factor: 0.01
  discomfort_weight: 10